#include "Graphic.h"

void G_Rat(){

	clrscr();
	setcolor(FOREGROUND_INTENSITY);
	cout << "                                                                               ";
	cout << endl;
	cout << "                                         ▁▂▃";
	setcolor(BACKGROUND_INTENSITY);
	cout << "     ";
	setcolor(0);
	cout << "                           ";
	cout << endl;
	cout << "                                   ";
	setcolor(FOREGROUND_RED);
	cout << "◢▅";
	setcolor(BACKGROUND_INTENSITY);
	cout << "         ";
	setcolor(0);
	cout << " ";
	setcolor(BACKGROUND_RED);
	cout << "▆";
	setcolor(BACKGROUND_INTENSITY);
	cout << "  ";
	setcolor(0);
	cout << "                          ";
	cout << endl;
	cout << "                                   ";
	setcolor(BACKGROUND_RED);
	cout << "    ";
	setcolor(BACKGROUND_INTENSITY);
	cout << "           ";
	setcolor(0);
	cout << " ";
	setcolor(BACKGROUND_INTENSITY);
	cout << "  ◥";
	setcolor(FOREGROUND_INTENSITY);
	cout << "▁▁                    ";
	cout << endl;
	cout << "                                    ";
	setcolor(BACKGROUND_RED);
	cout << "▆";
	setcolor(BACKGROUND_INTENSITY);
	cout << "                 ";
	setcolor(BACKGROUND_RED | FOREGROUND_GREEN | FOREGROUND_RED);
	cout << "◤";
	setcolor(BACKGROUND_RED | BACKGROUND_GREEN | FOREGROUND_RED);
	cout << "▄";
	setcolor(FOREGROUND_RED | BACKGROUND_INTENSITY);
	cout << "▇";
	setcolor(0);
	cout << "                  ";
	cout << endl;
	cout << "                                 ";
	setcolor(BACKGROUND_RED);
	cout << " ";
	setcolor(0);
	cout << "  ";
	setcolor(BACKGROUND_RED);
	cout << " ";
	setcolor(0);
	cout << "  ";
	setcolor(BACKGROUND_INTENSITY);
	cout << "              ";
	setcolor(BACKGROUND_RED | FOREGROUND_INTENSITY);
	cout << "▌    ";
	setcolor(FOREGROUND_RED);
	cout << "▊                  ";
	cout << endl;
	cout << "                                ";
	setcolor(BACKGROUND_RED);
	cout << "  ";
	setcolor(FOREGROUND_RED);
	cout << "▋";
	setcolor(BACKGROUND_RED);
	cout << " ";
	setcolor(0);
	cout << "    ";
	setcolor(BACKGROUND_INTENSITY);
	cout << "▅          ";
	setcolor(BACKGROUND_RED | FOREGROUND_INTENSITY);
	cout << "▌ ▁";
	setcolor(BACKGROUND_RED);
	cout << "◢";
	setcolor(0);
	cout << "                   ";
	cout << endl;
	cout << "                                 ";
	setcolor(BACKGROUND_RED);
	cout << "◣ ";
	setcolor(FOREGROUND_RED);
	cout << "▍      ";
	setcolor(BACKGROUND_INTENSITY);
	cout << "            ";
	setcolor(0);
	cout << "                       ";
	cout << endl;
	cout << "                                    ";
	setcolor(BACKGROUND_INTENSITY);
	cout << "                     ";
	setcolor(FOREGROUND_INTENSITY);
	cout << "◣                    ";
	cout << endl;
	cout << "                                    ";
	setcolor(BACKGROUND_INTENSITY);
	cout << "◣                     ";
	setcolor(FOREGROUND_INTENSITY);
	cout << "◣                  ";
	cout << endl;
	cout << "                                       ";
	setcolor(BACKGROUND_INTENSITY);
	cout << "▅                    ";
	setcolor(0);
	cout << "                  ";
	cout << endl;
	cout << "                                           ";
	setcolor(BACKGROUND_INTENSITY);
	cout << "▆                 ";
	setcolor(FOREGROUND_INTENSITY);
	cout << "▏               ";
	cout << endl;
	cout << "                                               ";
	setcolor(BACKGROUND_INTENSITY);
	cout << "                 ";
	setcolor(0);
	cout << "               ";
	cout << endl;
	cout << "                                               ";
	setcolor(BACKGROUND_INTENSITY);
	cout << "▎                ";
	setcolor(0);
	cout << "              ";
	cout << endl;
	cout << "                                               ";
	setcolor(BACKGROUND_INTENSITY);
	cout << "      ";
	setcolor(BACKGROUND_RED);
	cout << "  ";
	setcolor(BACKGROUND_INTENSITY);
	cout << "           ";
	setcolor(0);
	cout << "             ";
	cout << endl;
	cout << "                                              ";
	setcolor(BACKGROUND_INTENSITY);
	cout << "▋     ";
	setcolor(FOREGROUND_RED | BACKGROUND_INTENSITY);
	cout << "▊           ";
	setcolor(0);
	cout << "             ";
	cout << endl;
	cout << "                                               ";
	setcolor(BACKGROUND_INTENSITY);
	cout << "                  ";
	setcolor(FOREGROUND_INTENSITY);
	cout << "▌            ";
	cout << endl;
	cout << "                                             ";
	setcolor(BACKGROUND_INTENSITY);
	cout << "▊                   ";
	setcolor(0);
	cout << "             ";
	cout << endl;
	cout << "                                              ";
	setcolor(BACKGROUND_INTENSITY);
	cout << "                    ";
	setcolor(0);
	cout << "             ";
	cout << endl;
	cout << "                                              ";
	setcolor(BACKGROUND_INTENSITY);
	cout << "                   ";
	setcolor(FOREGROUND_INTENSITY);
	cout << "▏            ";
	cout << endl;
	cout << "                                               ";
	setcolor(BACKGROUND_INTENSITY);
	cout << "                   ";
	setcolor(BACKGROUND_RED);
	cout << "▃▂";
	setcolor(FOREGROUND_RED);
	cout << "▄▃";
	setcolor(FOREGROUND_GREEN | FOREGROUND_RED);
	cout << "▁   ";
	cout << endl;
	cout << "                                             ";
	setcolor(BACKGROUND_RED);
	cout << "◣ ";
	setcolor(FOREGROUND_RED | BACKGROUND_INTENSITY);
	cout << "▇              ";
	setcolor(0);
	cout << "       ";
	setcolor(BACKGROUND_RED);
	cout << "▇▆";
	setcolor(BACKGROUND_RED | BACKGROUND_GREEN);
	cout << "▅";
	setcolor(0);
	cout << "  ";
	cout << endl;
	cout << "                                                      ";
	setcolor(BACKGROUND_INTENSITY);
	cout << "▆";
	setcolor(BACKGROUND_RED);
	cout << " ▂▄";
	setcolor(BACKGROUND_INTENSITY);
	cout << "▆";
	setcolor(0);
	cout << "                ";
	cout << endl;
	cout << "                                                                               ";



	gotoxy(80, 25);
	return;
}

void G_Pika(){

	clrscr();
	setcolor(0);
	cout << "                                                              ";
	setcolor(BACKGROUND_RED);
	cout << " ";
	setcolor(FOREGROUND_RED);
	cout << "▏              ";
	cout << endl;
	cout << "                                   ▄▂                      ";
	setcolor(BACKGROUND_RED);
	cout << "   ";
	setcolor(0);
	cout << "               ";
	cout << endl;
	cout << "                                   ";
	setcolor(BACKGROUND_RED);
	cout << "◣   ";
	setcolor(BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY);
	cout << " ◥";
	setcolor(0);
	cout << "                ";
	setcolor(BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY);
	cout << "▌";
	setcolor(BACKGROUND_RED | FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_INTENSITY);
	cout << "◣ ";
	setcolor(FOREGROUND_INTENSITY);
	cout << "               ";
	cout << endl;
	cout << "                                      ";
	setcolor(BACKGROUND_RED);
	cout << "  ";
	setcolor(BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY);
	cout << "    ";
	setcolor(FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_INTENSITY);
	cout << "◣            ";
	setcolor(BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY);
	cout << "▊  ";
	setcolor(FOREGROUND_RED);
	cout << "▋               ";
	cout << endl;
	cout << "                                        ";
	setcolor(FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_INTENSITY);
	cout << "◥";
	setcolor(BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY);
	cout << "     ◥";
	setcolor(0);
	cout << "         ";
	setcolor(BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY);
	cout << "▌  ";
	setcolor(FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_INTENSITY);
	cout << "▌               ";
	cout << endl;
	cout << "                                           ";
	setcolor(BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY);
	cout << "◣▁       ";
	setcolor(FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_INTENSITY);
	cout << "▆▂ ";
	setcolor(BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY);
	cout << "  ";
	setcolor(FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_INTENSITY);
	cout << "▊                ";
	cout << endl;
	cout << "                                            ";
	setcolor(BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY);
	cout << "▊               ";
	setcolor(FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_INTENSITY);
	cout << "▌                ";
	cout << endl;
	cout << "                                             ";
	setcolor(FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_INTENSITY);
	cout << "▊ ";
	setcolor(BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY | FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY);
	cout << "▍           ";
	setcolor(FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_INTENSITY);
	cout << "▏                ";
	cout << endl;
	cout << "                                           ";
	setcolor(BACKGROUND_RED | BACKGROUND_INTENSITY);
	cout << "◤";
	setcolor(BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY);
	cout << "  ";
	setcolor(FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_INTENSITY);
	cout << "▄";
	setcolor(BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY | FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY);
	cout << "       ▂   ";
	setcolor(0);
	cout << "                  ";
	cout << endl;
	cout << "                                           ";
	setcolor(BACKGROUND_RED | BACKGROUND_INTENSITY);
	cout << "  ";
	setcolor(BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY);
	cout << "    ";
	setcolor(BACKGROUND_RED);
	cout << "  ";
	setcolor(BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY | FOREGROUND_RED);
	cout << "▄   ";
	setcolor(0);
	cout << "  ";
	setcolor(BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY);
	cout << "  ";
	setcolor(FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_INTENSITY);
	cout << "▏                 ";
	cout << endl;
	cout << "                                           ";
	setcolor(BACKGROUND_RED | BACKGROUND_INTENSITY | FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_INTENSITY);
	cout << "▃";
	setcolor(BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY);
	cout << "    ";
	setcolor(BACKGROUND_RED | BACKGROUND_INTENSITY);
	cout << "  ";
	setcolor(BACKGROUND_RED | FOREGROUND_RED | FOREGROUND_INTENSITY);
	cout << "▃ ";
	setcolor(BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY | FOREGROUND_RED | FOREGROUND_INTENSITY);
	cout << "    ▁";
	setcolor(FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_INTENSITY);
	cout << " ▁▃              ";
	cout << endl;
	cout << "                                          ▁";
	setcolor(BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY);
	cout << "    ";
	setcolor(BACKGROUND_RED | BACKGROUND_INTENSITY | FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_INTENSITY);
	cout << "▋   ";
	setcolor(BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY);
	cout << "    ";
	setcolor(BACKGROUND_RED | BACKGROUND_INTENSITY | FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_INTENSITY);
	cout << "◤";
	setcolor(BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY | FOREGROUND_RED | FOREGROUND_INTENSITY);
	cout << "▍   ";
	setcolor(FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_INTENSITY);
	cout << "▊             ";
	cout << endl;
	cout << "                                       ";
	setcolor(BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY);
	cout << "◤         ";
	setcolor(BACKGROUND_RED | BACKGROUND_INTENSITY | FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_INTENSITY);
	cout << "▅";
	setcolor(BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY);
	cout << "     ";
	setcolor(BACKGROUND_RED | BACKGROUND_INTENSITY | FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_INTENSITY);
	cout << "▂";
	setcolor(BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY);
	cout << "      ";
	setcolor(FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_INTENSITY);
	cout << "▃▂▁        ";
	cout << endl;
	cout << "                                      ";
	setcolor(BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY);
	cout << "▋                                ";
	setcolor(FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_INTENSITY);
	cout << "▆▄▁ ";
	cout << endl;
	cout << "                                       ";
	setcolor(BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY);
	cout << "◣                   ◢▏             ";
	setcolor(FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_INTENSITY);
	cout << "▋";
	cout << endl;
	cout << "                                          ";
	setcolor(BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY);
	cout << "               ";
	setcolor(FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_INTENSITY);
	cout << "◤   ";
	setcolor(BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY);
	cout << "              ◢";
	setcolor(FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_INTENSITY);
	cout << " ";
	cout << endl;
	cout << "                                        ";
	setcolor(BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY);
	cout << "▋              ";
	setcolor(FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_INTENSITY);
	cout << "▋ ▃";
	setcolor(BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY);
	cout << "▏";
	setcolor(FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_INTENSITY);
	cout << "▊ ";
	setcolor(BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY);
	cout << "▆▃▁  ◢";
	setcolor(FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_INTENSITY);
	cout << "   ";
	cout << endl;
	cout << "                                        ";
	setcolor(BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY);
	cout << "▎              ";
	setcolor(FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_INTENSITY);
	cout << "▋ ";
	setcolor(BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY);
	cout << "    ";
	setcolor(FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_INTENSITY);
	cout << "▎              ";
	cout << endl;
	cout << "                                        ";
	setcolor(BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY);
	cout << "                 ";
	setcolor(FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_INTENSITY);
	cout << "◣";
	setcolor(BACKGROUND_RED);
	cout << " ";
	setcolor(FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_INTENSITY);
	cout << "▍                 ";
	cout << endl;
	cout << "                                      ";
	setcolor(BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY);
	cout << "▌                 ";
	setcolor(FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_INTENSITY);
	cout << "▊";
	setcolor(BACKGROUND_RED);
	cout << "▄";
	setcolor(0);
	cout << "                  ";
	cout << endl;
	cout << "                                      ";
	setcolor(BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY);
	cout << "▋                 ";
	setcolor(FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_INTENSITY);
	cout << "▊                    ";
	cout << endl;
	cout << "                                      ◢";
	setcolor(BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY);
	cout << "    ▄▄▄▃▁   ";
	setcolor(FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_INTENSITY);
	cout << "▋                    ";
	cout << endl;
	cout << "                                      ";
	setcolor(BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY);
	cout << "▆▇";
	setcolor(0);
	cout << "             ";
	setcolor(BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY);
	cout << "▄▃";
	setcolor(FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_INTENSITY);
	cout << "◣                  ";

	gotoxy(80, 25);
	return;
}

void G_Logo(){

	setcolor(FOREGROUND_INTENSITY | FOREGROUND_RED);
	gotoxy(6, 3);
	cout << "██◣　◢█◣　███";
	gotoxy(6, 4);
	cout << "█　█　█　█　　▇";
	gotoxy(6, 5);
	cout << "██◤　███　　█";
	gotoxy(6, 6);
	cout << "█◥◣　█　█　　█";

	setcolor(FOREGROUND_INTENSITY | FOREGROUND_GREEN | FOREGROUND_RED);
	gotoxy(12, 8);
	cout << "▆";
	gotoxy(12, 9);
	cout << "▅　█◢▉";
	gotoxy(12, 10);
	cout << "█　█◤▉";
	gotoxy(12, 11);
	cout << "█　█　▉";

	setcolor(FOREGROUND_INTENSITY | FOREGROUND_RED);
	gotoxy(3, 13);
	cout << "█　　█　◢█◣　███　███";
	gotoxy(3, 14);
	cout << "█◣◢█　█　█　　◢◤　█▄▄";
	gotoxy(3, 15);
	cout << "█◥◤█　███　◢◤　　█";
	gotoxy(3, 16);
	cout << "█　　█　█　█　███　███";


	gotoxy(80, 25);
	return;
}

void G_Menu(int opt){

	setcolor(FOREGROUND_INTENSITY | FOREGROUND_GREEN | FOREGROUND_BLUE);
	gotoxy(12, 19);
	cout << "標準模式";
	gotoxy(12, 20);
	cout << "額外模式";
	gotoxy(12, 21);
	cout << "離　　開";

	setcolor(FOREGROUND_INTENSITY | FOREGROUND_RED | FOREGROUND_BLUE);
	gotoxy(9, 18 + opt);
	cout << "◆";

	gotoxy(80, 25);
	return;
}

void G_MOption(int density, int complex, int roadc, int wallc){

	clrscr();

	setcolor(FOREGROUND_INTENSITY | FOREGROUND_GREEN | FOREGROUND_BLUE);
	gotoxy(7, 7);
	cout << "地圖設定";
	setcolor(FOREGROUND_INTENSITY | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_RED);
	gotoxy(5, 9);
	cout << "------------------------------------------------------------------------";
	gotoxy(7, 11);
	cout << "密集程度";
	gotoxy(7, 13);
	cout << "複雜程度";
	gotoxy(7, 15);
	cout << "通路顏色";
	gotoxy(7, 17);
	cout << "牆壁顏色";

	setcolor(FOREGROUND_GREEN | FOREGROUND_RED | FOREGROUND_BLUE);
	gotoxy(23, 11);
	cout << "10     20     30     40     50";
	gotoxy(23, 13);
	cout << "1      2      3      4";
	gotoxy(23, 15);
	setcolor(FOREGROUND_RED);
	cout << "●     ";
	setcolor(FOREGROUND_GREEN | FOREGROUND_RED);
	cout << "●     ";
	setcolor(FOREGROUND_GREEN);
	cout << "●     ";
	setcolor(FOREGROUND_GREEN | FOREGROUND_BLUE);
	cout << "●     ";
	setcolor(FOREGROUND_BLUE);
	cout << "●     ";
	setcolor(FOREGROUND_RED | FOREGROUND_BLUE);
	cout << "●     ";
	setcolor(FOREGROUND_INTENSITY);
	cout << "○";
	gotoxy(23, 17);
	setcolor(FOREGROUND_RED);
	cout << "●     ";
	setcolor(FOREGROUND_GREEN | FOREGROUND_RED);
	cout << "●     ";
	setcolor(FOREGROUND_GREEN);
	cout << "●     ";
	setcolor(FOREGROUND_GREEN | FOREGROUND_BLUE);
	cout << "●     ";
	setcolor(FOREGROUND_BLUE);
	cout << "●     ";
	setcolor(FOREGROUND_RED | FOREGROUND_BLUE);
	cout << "●     ";
	setcolor(FOREGROUND_INTENSITY);
	cout << "○";

	setcolor(FOREGROUND_INTENSITY);
	gotoxy(14 + density * 7, 11);
	cout << "[";
	gotoxy(19 + density * 7, 11);
	cout << "]";
	gotoxy(14 + complex * 7, 13);
	cout << "[";
	gotoxy(19 + complex * 7, 13);
	cout << "]";
	gotoxy(14 + roadc * 7, 15);
	cout << "[";
	gotoxy(19 + roadc * 7, 15);
	cout << "]";
	gotoxy(14 + wallc * 7, 17);
	cout << "[";
	gotoxy(19 + wallc * 7, 17);
	cout << "]";

	gotoxy(80, 25);
	return;
}

void G_ROption(int ratai, int delay, int ratc, int pathc, int flag){

	clrscr();

	setcolor(FOREGROUND_INTENSITY | FOREGROUND_GREEN | FOREGROUND_BLUE);
	gotoxy(7, 7);
	cout << "老鼠設定";
	setcolor(FOREGROUND_INTENSITY | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_RED);
	gotoxy(5, 9);
	cout << "------------------------------------------------------------------------";
	gotoxy(7, 11);
	cout << "選路方式";
	gotoxy(7, 13);
	cout << "延遲時間";
	gotoxy(7, 15);
	cout << "老鼠顏色";
	gotoxy(7, 17);
	cout << "軌跡顏色";

	setcolor(FOREGROUND_GREEN | FOREGROUND_RED | FOREGROUND_BLUE);
	gotoxy(23, 11);
	cout << "A      B      C      D";
	setcolor((flag == 1 ? FOREGROUND_INTENSITY | FOREGROUND_GREEN | FOREGROUND_RED : FOREGROUND_GREEN | FOREGROUND_RED | FOREGROUND_BLUE));
	cout << "     " << (flag == 1 ? "PIKA" : " ?");
	setcolor(FOREGROUND_GREEN | FOREGROUND_RED | FOREGROUND_BLUE);
	gotoxy(23, 13);
	cout << "10     20     30     40     50     60     70";
	gotoxy(23, 15);
	setcolor(FOREGROUND_INTENSITY | FOREGROUND_RED);
	cout << "●     ";
	setcolor(FOREGROUND_INTENSITY | FOREGROUND_GREEN | FOREGROUND_RED);
	cout << "●     ";
	setcolor(FOREGROUND_INTENSITY | FOREGROUND_GREEN);
	cout << "●     ";
	setcolor(FOREGROUND_INTENSITY | FOREGROUND_GREEN | FOREGROUND_BLUE);
	cout << "●     ";
	setcolor(FOREGROUND_INTENSITY | FOREGROUND_BLUE);
	cout << "●     ";
	setcolor(FOREGROUND_INTENSITY | FOREGROUND_RED | FOREGROUND_BLUE);
	cout << "●     ";
	setcolor(FOREGROUND_INTENSITY | FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_GREEN);
	cout << "●";
	gotoxy(23, 17);
	setcolor(FOREGROUND_RED);
	cout << "●     ";
	setcolor(FOREGROUND_GREEN | FOREGROUND_RED);
	cout << "●     ";
	setcolor(FOREGROUND_GREEN);
	cout << "●     ";
	setcolor(FOREGROUND_GREEN | FOREGROUND_BLUE);
	cout << "●     ";
	setcolor(FOREGROUND_BLUE);
	cout << "●     ";
	setcolor(FOREGROUND_RED | FOREGROUND_BLUE);
	cout << "●     ";
	setcolor(FOREGROUND_INTENSITY);
	cout << "○";

	setcolor(FOREGROUND_INTENSITY);
	gotoxy(14 + ratai * 7, 11);
	cout << "[";
	gotoxy(19 + ratai * 7, 11);
	cout << "]";
	gotoxy(14 + delay * 7, 13);
	cout << "[";
	gotoxy(19 + delay * 7, 13);
	cout << "]";
	gotoxy(14 + ratc * 7, 15);
	cout << "[";
	gotoxy(19 + ratc * 7, 15);
	cout << "]";
	gotoxy(14 + pathc * 7, 17);
	cout << "[";
	gotoxy(19 + pathc * 7, 17);
	cout << "]";

	gotoxy(80, 25);
	return;
}

void G_Result(){

	clrscr();

	setcolor(FOREGROUND_INTENSITY | FOREGROUND_GREEN | FOREGROUND_BLUE);
	gotoxy(7, 8);
	cout << "紀　　錄";
	setcolor(FOREGROUND_INTENSITY | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_RED);
	gotoxy(5, 9);
	cout << "----------------------------";
	gotoxy(7, 10);
	cout << "地圖流水號";
	gotoxy(7, 11);
	cout << "密集程度";
	gotoxy(7, 12);
	cout << "複雜程度";
	gotoxy(7, 13);
	cout << "選路方式";
	gotoxy(7, 14);
	cout << "延遲時間";
	gotoxy(7, 15);
	cout << "理論最小步數";
	gotoxy(7, 16);
	cout << "使用步數";
	gotoxy(7, 17);
	cout << "使用時間";
	gotoxy(7, 18);
	cout << "死路次數";
	gotoxy(5, 19);
	cout << "----------------------------";


	setcolor(FOREGROUND_INTENSITY | FOREGROUND_RED | FOREGROUND_BLUE);
	gotoxy(47, 12);
	cout << "再次進行迷宮";
	gotoxy(47, 13);
	cout << "重新產生地圖後進行迷宮";
	gotoxy(47, 14);
	cout << "變更地圖設定";
	gotoxy(47, 15);
	cout << "變更老鼠設定";
	gotoxy(47, 16);
	cout << "返回標題";
	gotoxy(47, 17);
	cout << "離開";

	setcolor(FOREGROUND_INTENSITY | FOREGROUND_GREEN);
	gotoxy(44, 12);
	cout << "◆";

	gotoxy(80, 25);
	return;
}